import { Firm, Product, Language, Address, Driver } from '../types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'uz', name: 'Uzbek', nativeName: 'O\'zbekcha' },
];

export const MOCK_FIRMS: Firm[] = [
  {
    id: '1',
    name: 'AQUAwater',
    logo: 'https://i.postimg.cc/1tYzmgBX/Chat-GPT-Image-30-2025-16-35-32.png',
    rating: 4.8,
    deliveryTime: '15-25 min',
    minOrder: 5000,
    deliveryFee: 5000,
  },
  {
    id: '2',
    name: 'OceanWater',
    logo: 'https://i.postimg.cc/LsKCWNM6/Chat-GPT-Image-30-2025-16-43-13.png',
    rating: 4.6,
    deliveryTime: '20-30 min',
    minOrder: 4000,
    deliveryFee: 4000,
  },
  {
    id: '3',
    name: 'Zam-Zam Water',
    logo: 'https://i.postimg.cc/vZbwKrwy/Chat-GPT-Image-30-2025-16-57-55.png',
    rating: 5.0,
    deliveryTime: '10-20 min',
    minOrder: 6000,
    deliveryFee: 6000,
  },
  {
    id: '4',
    name: 'Crystal Water',
    logo: 'https://i.postimg.cc/Prc8z5g1/Chat-GPT-Image-30-2025-17-05-11.png',
    rating: 4.7,
    deliveryTime: '25-35 min',
    minOrder: 3500,
    deliveryFee: 3500,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // AQUAwater products
  {
    id: '1-1',
    firmId: '1',
    name: 'AQUAwater 5L Bottle',
    description: 'Premium purified water in convenient 5L bottle',
    price: 5000,
    image: 'https://i.postimg.cc/rFSrRVKf/Chat-GPT-Image-30-2025-09-02-41.png',
    volume: '5L',
    inStock: true,
  },
  {
    id: '1-2',
    firmId: '1',
    name: 'AQUAwater 10L Bottle',
    description: 'Family size purified water bottle',
    price: 10000,
    image: 'https://i.postimg.cc/sxP5zsWH/Chat-GPT-Image-30-2025-09-32-17.png',
    volume: '10L',
    inStock: true,
  },
  {
    id: '1-3',
    firmId: '1',
    name: 'AQUAwater 19L Bottle',
    description: 'Large office/home water dispenser bottle',
    price: 15000,
    image: 'https://i.postimg.cc/g00sKXhz/Chat-GPT-Image-30-2025-09-24-58.png',
    volume: '19L',
    inStock: true,
  },
  {
    id: '1-4',
    firmId: '1',
    name: 'AQUAwater 0.5L Bottle',
    description: 'Portable water bottle for on-the-go',
    price: 3000,
    image: 'https://i.postimg.cc/MKv8J6vP/Chat-GPT-Image-30-2025-17-27-51.png',
    volume: '0.5L',
    inStock: true,
  },

  // OceanWater products
  {
    id: '2-1',
    firmId: '2',
    name: 'OceanWater 5L Bottle',
    description: 'Natural spring water from mountain sources',
    price: 7000,
    image: 'https://i.postimg.cc/qvd7Q67V/Chat-GPT-Image-30-2025-18-09-33.png',
    volume: '5L',
    inStock: true,
  },
  {
    id: '2-2',
    firmId: '2',
    name: 'OceanWater 10L Bottle',
    description: 'Family size spring water bottle',
    price: 10000,
    image: 'https://i.postimg.cc/nz89mFP0/Chat-GPT-Image-30-2025-18-16-55.png',
    volume: '10L',
    inStock: true,
  },
  {
    id: '2-3',
    firmId: '2',
    name: 'OceanWater 19L Bottle',
    description: 'Large spring water dispenser bottle',
    price: 15000,
    image: 'https://i.postimg.cc/Jz7f1R6H/Chat-GPT-Image-30-2025-18-05-25.png',
    volume: '19L',
    inStock: true,
  },
  {
    id: '2-4',
    firmId: '2',
    name: 'OceanWater 0.5L Bottle',
    description: 'Portable spring water bottle',
    price: 3000,
    image: 'https://i.postimg.cc/PJj6SkPM/Chat-GPT-Image-30-2025-18-19-32.png',
    volume: '0.5L',
    inStock: true,
  },

  // Zam-Zam Water products
  {
    id: '3-1',
    firmId: '3',
    name: 'Zam-Zam Water 5L Bottle',
    description: 'Ultra-pure filtered water with advanced purification',
    price: 5000,
    image: 'https://i.postimg.cc/Z5ZN75bg/Chat-GPT-Image-30-2025-18-36-33.png',
    volume: '5L',
    inStock: true,
  },
  {
    id: '3-2',
    firmId: '3',
    name: 'Zam-Zam Water 10L Bottle',
    description: 'Family size ultra-pure filtered water',
    price: 10000,
    image: 'https://i.postimg.cc/gkYfqv96/Chat-GPT-Image-30-2025-18-29-48.png',
    volume: '10L',
    inStock: true,
  },
  {
    id: '3-3',
    firmId: '3',
    name: 'Zam-Zam Water 19L Bottle',
    description: 'Large ultra-pure filtered water dispenser bottle',
    price: 15000,
    image: 'https://i.postimg.cc/TYsBT4wq/Chat-GPT-Image-30-2025-18-43-45-1.png',
    volume: '19L',
    inStock: true,
  },
  {
    id: '3-4',
    firmId: '3',
    name: 'Zam-Zam Water 0.5L Bottle',
    description: 'Portable ultra-pure water bottle',
    price: 3000,
    image: 'https://i.postimg.cc/5tdGCQ8X/Chat-GPT-Image-30-2025-18-44-25.png',
    volume: '0.5L',
    inStock: true,
  },

  // Crystal Water products
  {
    id: '4-1',
    firmId: '4',
    name: 'CrystalClear 5L Bottle',
    description: 'Natural mineral water with essential minerals',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=300&h=300&fit=crop',
    volume: '5L',
    inStock: false,
  },
  {
    id: '4-2',
    firmId: '4',
    name: 'CrystalClear 10L Bottle',
    description: 'Family size natural mineral water',
    price: 11000,
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=300&h=300&fit=crop',
    volume: '10L',
    inStock: false,
  },
  {
    id: '4-3',
    firmId: '4',
    name: 'CrystalClear 19L Bottle',
    description: 'Large natural mineral water dispenser bottle',
    price: 20000,
    image: 'https://e7.pngegg.com/pngimages/725/706/png-clipart-drinking-water-mineral-water-bottles-mineral-water-thumbnail.png',
    volume: '19L',
    inStock: false,
  },
];

export const MOCK_ADDRESSES: Address[] = [
  {
    id: '1',
    title: 'Home',
    address: 'Tashkent, Chorsu District, 123 Main Street',
    lat: 41.2995,
    lng: 69.2401,
    isDefault: true,
  },
  {
    id: '2',
    title: 'Work',
    address: 'Tashkent, Yunusabad District, 456 Central Avenue',
    lat: 41.3111,
    lng: 69.2797,
    isDefault: false,
  },
  {
    id: '3',
    title: 'Parent\'s House',
    address: 'Tashkent, Mirabad District, 789 Business Center',
    lat: 41.2858,
    lng: 69.2034,
    isDefault: false,
  },
];

export const MOCK_DRIVER: Driver = {
  id: '1',
  name: 'Ali Karimov',
  phone: '+998901234567',
  photo: '👨‍💼',
  rating: 4.9,
  vehicleNumber: '01 A 123 BC',
};
