import { Firm, Product, Language, Address, Driver } from '../types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'uz', name: 'Uzbek', nativeName: 'O\'zbekcha', flag: '🇺🇿' },
  { code: 'kaa', name: 'Qaraqalpaq', nativeName: 'Qaraqalpaq tili', flag: '🇰🇬' },
];

export const MOCK_FIRMS: Firm[] = [
  {
    id: '1',
    name: 'AQUAwater',
    logo: require('../assets/firms/aquawater-logo.png'),
    rating: 4.8,
    deliveryTime: '15-25 min',
    minOrder: 5000,
    deliveryFee: 5000,
    bottleDeposit: 5000,
    location: 'Tashkent',
    promotions: [
      { label: '-10% delivery', value: 'delivery-discount', color: 'green' },
      { label: '-20% bottles', value: 'bottles-discount', color: 'blue' },
    ],
  },
  {
    id: '2',
    name: 'OceanWater',
    logo: require('../assets/firms/oceanwater-logo.png'),
    rating: 4.6,
    deliveryTime: '20-30 min',
    minOrder: 4000,
    deliveryFee: 4000,
    bottleDeposit: 4000,
    location: 'Tashkent',
    promotions: [
      { label: 'Free delivery', value: 'free-delivery', color: 'green' },
    ],
  },
  {
    id: '3',
    name: 'Zam-Zam Water',
    logo: require('../assets/firms/zamzam-logo.png'),
    rating: 5.0,
    deliveryTime: '10-20 min',
    minOrder: 6000,
    deliveryFee: 6000,
    bottleDeposit: 6000,
    location: 'Tashkent',
    promotions: [
      { label: 'Premium quality', value: 'premium', color: 'blue' },
    ],
  },
  {
    id: '4',
    name: 'Crystal Water',
    logo: require('../assets/firms/crystal-logo.png'),
    rating: 4.7,
    deliveryTime: '25-35 min',
    minOrder: 3500,
    deliveryFee: 3500,
    bottleDeposit: 3500,
    location: 'Tashkent',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // AQUAwater products
  {
    id: '1-1',
    firmId: '1',
    name: 'AQUAwater 5L Bottle',
    description: 'Premium purified water in convenient 5L bottle',
    price: 5000,
    image: require('../assets/products/aqua-5l.png'),
    volume: '5L',
    inStock: true,
  },
  {
    id: '1-2',
    firmId: '1',
    name: 'AQUAwater 10L Bottle',
    description: 'Family size purified water bottle',
    price: 10000,
    image: require('../assets/products/aqua-10l.png'),
    volume: '10L',
    inStock: true,
  },
  {
    id: '1-3',
    firmId: '1',
    name: 'AQUAwater 19L Bottle',
    description: 'Large office/home water dispenser bottle',
    price: 15000,
    image: require('../assets/products/aqua-19l.png'),
    volume: '19L',
    inStock: true,
  },
  {
    id: '1-4',
    firmId: '1',
    name: 'AQUAwater 0.5L Bottle',
    description: 'Portable water bottle for on-the-go',
    price: 3000,
    image: require('../assets/products/aqua-0.5l.png'),
    volume: '0.5L',
    inStock: true,
  },

  // OceanWater products
  {
    id: '2-1',
    firmId: '2',
    name: 'OceanWater 5L Bottle',
    description: 'Natural spring water from mountain sources',
    price: 7000,
    image: require('../assets/products/ocean-5l.png'),
    volume: '5L',
    inStock: true,
  },
  {
    id: '2-2',
    firmId: '2',
    name: 'OceanWater 10L Bottle',
    description: 'Family size spring water bottle',
    price: 10000,
    image: require('../assets/products/ocean-10l.png'),
    volume: '10L',
    inStock: true,
  },
  {
    id: '2-3',
    firmId: '2',
    name: 'OceanWater 19L Bottle',
    description: 'Large spring water dispenser bottle',
    price: 15000,
    image: require('../assets/products/ocean-19l.png'),
    volume: '19L',
    inStock: true,
  },
  {
    id: '2-4',
    firmId: '2',
    name: 'OceanWater 0.5L Bottle',
    description: 'Portable spring water bottle',
    price: 3000,
    image: require('../assets/products/ocean-0.5l.png'),
    volume: '0.5L',
    inStock: true,
  },

  // Zam-Zam Water products
  {
    id: '3-1',
    firmId: '3',
    name: 'Zam-Zam Water 5L Bottle',
    description: 'Ultra-pure filtered water with advanced purification',
    price: 5000,
    image: require('../assets/products/zamzam-5l.png'),
    volume: '5L',
    inStock: true,
  },
  {
    id: '3-2',
    firmId: '3',
    name: 'Zam-Zam Water 10L Bottle',
    description: 'Family size ultra-pure filtered water',
    price: 10000,
    image: require('../assets/products/zamzam-10l.png'),
    volume: '10L',
    inStock: true,
  },
  {
    id: '3-3',
    firmId: '3',
    name: 'Zam-Zam Water 19L Bottle',
    description: 'Large ultra-pure filtered water dispenser bottle',
    price: 15000,
    image: require('../assets/products/zamzam-19l.png'),
    volume: '19L',
    inStock: true,
  },
  {
    id: '3-4',
    firmId: '3',
    name: 'Zam-Zam Water 0.5L Bottle',
    description: 'Portable ultra-pure water bottle',
    price: 3000,
    image: require('../assets/products/zamzam-0.5l.png'),
    volume: '0.5L',
    inStock: true,
  },

  // Crystal Water products
  {
    id: '4-1',
    firmId: '4',
    name: 'CrystalClear 5L Bottle',
    description: 'Natural mineral water with essential minerals',
    price: 6000,
    image: require('../assets/products/crystal-19l.png'),
    volume: '5L',
    inStock: false,
  },
  {
    id: '4-2',
    firmId: '4',
    name: 'CrystalClear 10L Bottle',
    description: 'Family size natural mineral water',
    price: 11000,
    image: require('../assets/products/crystal-19l.png'),
    volume: '10L',
    inStock: false,
  },
  {
    id: '4-3',
    firmId: '4',
    name: 'CrystalClear 19L Bottle',
    description: 'Large natural mineral water dispenser bottle',
    price: 20000,
    image: require('../assets/products/crystal-19l.png'),
    volume: '19L',
    inStock: false,
  },
];

export const MOCK_ADDRESSES: Address[] = [];

export const MOCK_DRIVER: Driver = {
  id: '1',
  name: 'Isakov Musabek',
  phone: '+998901234567',
  photo: '👨‍💼',
  rating: 4.9,
  vehicleNumber: '95K401XA',
  company: 'AQUAwater',
};
