// file: lib/mockData.ts

import {
  Client,
  Driver,
  Order,
  Staff,
  Region,
  Transaction,
  Firm,
  Product,
} from "@/types";

// Mock Data Storage
export const mockClients: Client[] = [
  {
    id: "c1",
    name: "Aziz Karimov",
    phone: "+998901234567",
    email: "aziz@example.com",
    address: "Chilanzar 10, apt 45, Tashkent",
    firmId: "1",
    type: "B2C",
    totalOrders: 45,
    revenue: 1350,
    createdAt: "2024-01-15T10:00:00Z",
    lastOrderAt: new Date().toISOString(),
  },
  {
    id: "c2",
    name: "Nigora Rahimova",
    phone: "+998901234568",
    email: "nigora@example.com",
    address: "Yunusabad 5, house 12, Tashkent",
    firmId: "1",
    type: "B2C",
    totalOrders: 32,
    revenue: 960,
    createdAt: "2024-02-10T10:00:00Z",
    lastOrderAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "c3",
    name: "Tech Solutions LLC",
    phone: "+998712345678",
    email: "office@techsolutions.uz",
    address: "Amir Temur 45, Business Center, Tashkent",
    firmId: "1",
    type: "B2B",
    totalOrders: 150,
    revenue: 15000,
    createdAt: "2023-12-01T10:00:00Z",
    lastOrderAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "c4",
    name: "Tashkent City Hall",
    phone: "+998712501010",
    email: "procurement@tashkent.gov.uz",
    address: "Mustakillik Square 1, Tashkent",
    firmId: "1",
    type: "B2G",
    totalOrders: 250,
    revenue: 35000,
    createdAt: "2023-11-15T10:00:00Z",
    lastOrderAt: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const mockDrivers: Driver[] = [
  {
    id: "drv-001",
    name: "Rustam Aliyev",
    phone: "+998901234567",
    firmId: "1",
    firmName: "AquaPure Tashkent",
    status: "DELIVERING",
    carPlate: "01A123BC",
    city: "Tashkent",
  },
  {
    id: "drv-002",
    name: "Shohrat Kamolov",
    phone: "+998901234568",
    firmId: "1",
    firmName: "AquaPure Tashkent",
    status: "ONLINE",
    carPlate: "01B456DE",
    city: "Tashkent",
  },
  {
    id: "drv-003",
    name: "Karim Yusupov",
    phone: "+998901234569",
    firmId: "1",
    firmName: "AquaPure Tashkent",
    status: "OFFLINE",
    carPlate: "01C789FG",
    city: "Samarkand",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    firmId: "1",
    firmName: "AquaPure Tashkent",
    clientName: "Aziz Karimov",
    address: "Chilanzar 10, apt 45, Tashkent",
    status: "ON_THE_WAY",
    createdAt: new Date().toISOString(),
  },
  {
    id: "ord-002",
    firmId: "1",
    firmName: "AquaPure Tashkent",
    clientName: "Nigora Rahimova",
    address: "Yunusabad 5, house 12, Tashkent",
    status: "DELIVERED",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "ord-003",
    firmId: "1",
    firmName: "AquaPure Tashkent",
    clientName: "Rustam Nazarov",
    address: "Mirzo Ulugbek 23, Tashkent",
    status: "PENDING",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const mockStaff: Staff[] = [
  {
    id: "staff-001",
    firmId: "1",
    name: "Sardor Rahimov",
    role: "OWNER",
    phone: "+998901111111",
    email: "sardor@aquapure.uz",
    city: "Tashkent",
    active: true,
    createdAt: "2023-01-10T10:00:00Z",
  },
  {
    id: "staff-002",
    firmId: "1",
    name: "Malika Azimova",
    role: "MANAGER",
    phone: "+998902222222",
    email: "malika@aquapure.uz",
    city: "Tashkent",
    active: true,
    createdAt: "2023-02-15T10:00:00Z",
  },
  {
    id: "staff-003",
    firmId: "1",
    name: "Bobur Karimov",
    role: "OPERATOR",
    phone: "+998903333333",
    email: "bobur@aquapure.uz",
    city: "Samarkand",
    active: true,
    createdAt: "2023-03-20T10:00:00Z",
  },
];

export const mockRegions: Region[] = [
  {
    id: "reg-001",
    firmId: "1",
    city: "Tashkent",
    activeDrivers: 8,
    totalOrders: 1250,
    revenue: 37500,
    districts: [
      {
        id: "dist-001",
        name: "Chilanzar",
        regionId: "reg-001",
        deliveryFee: 15000,
        estimatedTime: 30,
        active: true,
      },
      {
        id: "dist-002",
        name: "Yunusabad",
        regionId: "reg-001",
        deliveryFee: 12000,
        estimatedTime: 25,
        active: true,
      },
    ],
  },
  {
    id: "reg-002",
    firmId: "1",
    city: "Samarkand",
    activeDrivers: 4,
    totalOrders: 580,
    revenue: 17400,
    districts: [
      {
        id: "dist-006",
        name: "Old City",
        regionId: "reg-002",
        deliveryFee: 15000,
        estimatedTime: 30,
        active: true,
      },
    ],
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    firmId: "1",
    type: "REVENUE",
    category: "Water Delivery",
    amount: 50000,
    description: "Monthly B2B contract payment",
    date: new Date().toISOString(),
    orderId: "ord-001",
  },
  {
    id: "txn-002",
    firmId: "1",
    type: "EXPENSE",
    category: "Fuel",
    amount: 15000,
    description: "Driver fuel costs",
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "txn-003",
    firmId: "1",
    type: "REVENUE",
    category: "Water Delivery",
    amount: 30000,
    description: "B2C deliveries - Tashkent",
    date: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const mockFirms: Firm[] = [
  {
    id: "1",
    name: "AquaPure Tashkent",
    city: "Tashkent",
    status: "ACTIVE",
    clientsCount: 245,
    ordersCount: 1850,
    driversCount: 12,
    createdAt: "2023-01-10T10:00:00Z",
  },
  {
    id: "2",
    name: "Crystal Water Samarkand",
    city: "Samarkand",
    status: "ACTIVE",
    clientsCount: 180,
    ordersCount: 920,
    driversCount: 8,
    createdAt: "2023-02-20T10:00:00Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    firmId: "1",
    name: "AQUAwater 19L Bottle",
    description: "Large office/home water dispenser bottle",
    price: 15000,
    unit: "bottle",
    volume: "19L",
    image: "https://i.postimg.cc/g00sKXhz/Chat-GPT-Image-30-2025-09-24-58.png",
    inStock: true,
    stockQuantity: 250,
    minOrder: 1,
    category: "Water",
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "prod-002",
    firmId: "1",
    name: "AQUAwater 5L Bottle",
    description: "Premium purified water in convenient 5L bottle",
    price: 5000,
    unit: "bottle",
    volume: "5L",
    image: "https://i.postimg.cc/rFSrRVKf/Chat-GPT-Image-30-2025-09-02-41.png",
    inStock: true,
    stockQuantity: 180,
    minOrder: 2,
    category: "Water",
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "prod-003",
    firmId: "1",
    name: "AQUAwater 10L Bottle",
    description: "Family size purified water bottle",
    price: 10000,
    unit: "bottle",
    volume: "10L",
    image: "https://i.postimg.cc/sxP5zsWH/Chat-GPT-Image-30-2025-09-32-17.png",
    inStock: true,
    stockQuantity: 150,
    minOrder: 1,
    category: "Water",
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "prod-004",
    firmId: "1",
    name: "AQUAwater 0.5L Bottle",
    description: "Portable 0.5L bottle. Great for personal use and on-the-go.",
    price: 3000,
    unit: "bottle",
    volume: "0.5L",
    image: "https://i.postimg.cc/MKv8J6vP/Chat-GPT-Image-30-2025-17-27-51.png",
    inStock: true,
    stockQuantity: 120,
    minOrder: 1,
    category: "Water",
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "prod-005",
    firmId: "1",
    name: "Water Dispenser - Floor Standing",
    description: "Hot and cold water dispenser. Perfect for offices. Installation included.",
    price: 450000,
    unit: "unit",
    volume: "N/A",
    inStock: true,
    stockQuantity: 15,
    minOrder: 1,
    category: "Equipment",
    createdAt: "2023-02-10T10:00:00Z",
  },
  {
    id: "prod-006",
    firmId: "1",
    name: "Water Dispenser - Tabletop",
    description: "Compact tabletop water dispenser. Space-saving design for small offices.",
    price: 280000,
    unit: "unit",
    volume: "N/A",
    inStock: true,
    stockQuantity: 22,
    minOrder: 1,
    category: "Equipment",
    createdAt: "2023-02-10T10:00:00Z",
  },
  {
    id: "prod-006",
    firmId: "1",
    name: "Water Pump (Manual)",
    description: "Manual hand pump for 19L bottles. Durable and easy to use.",
    price: 25000,
    unit: "unit",
    volume: "N/A",
    inStock: true,
    stockQuantity: 85,
    minOrder: 1,
    category: "Accessories",
    createdAt: "2023-02-20T10:00:00Z",
  },
  {
    id: "prod-007",
    firmId: "1",
    name: "Electric Water Pump",
    description: "Electric pump for 19L bottles. USB rechargeable, automatic dispensing.",
    price: 65000,
    unit: "unit",
    volume: "N/A",
    inStock: true,
    stockQuantity: 42,
    minOrder: 1,
    category: "Accessories",
    createdAt: "2023-02-20T10:00:00Z",
  },
  {
    id: "prod-008",
    firmId: "1",
    name: "Bottle Stand with Shelf",
    description: "Sturdy metal stand for 19L bottles with storage shelf.",
    price: 95000,
    unit: "unit",
    volume: "N/A",
    inStock: true,
    stockQuantity: 28,
    minOrder: 1,
    category: "Accessories",
    createdAt: "2023-03-01T10:00:00Z",
  },
  {
    id: "prod-009",
    firmId: "1",
    name: "Sparkling Water 19L",
    description: "Premium sparkling water in 19L bottle. Perfect for special occasions.",
    price: 45000,
    unit: "bottle",
    volume: "19L",
    image: "https://i.postimg.cc/g00sKXhz/Chat-GPT-Image-30-2025-09-24-58.png",
    inStock: true,
    stockQuantity: 45,
    minOrder: 1,
    category: "Water",
    createdAt: "2023-03-15T10:00:00Z",
  },
  {
    id: "prod-010",
    firmId: "1",
    name: "Monthly Subscription (8x 19L)",
    description: "Monthly package: 8 bottles of 19L water delivered weekly. Best value!",
    price: 220000,
    unit: "subscription",
    volume: "19L",
    image: "https://i.postimg.cc/g00sKXhz/Chat-GPT-Image-30-2025-09-24-58.png",
    inStock: true,
    stockQuantity: 1000,
    minOrder: 1,
    category: "Water",
    createdAt: "2023-04-01T10:00:00Z",
  },
];
